/**
 * ZK Proof Setup — paths and configuration
 *
 * This module provides paths to the compiled circuit artifacts
 * generated by circom and the snarkjs trusted setup.
 *
 * Circuit: vote_verifier.circom
 * - Proves that vote count >= quorum without revealing individual votes
 * - Supports up to 64 voters (maxVoters parameter)
 * - Uses Groth16 proving system on BN128 curve
 */

import * as path from 'path';

// Max voters supported by the compiled circuit
export const MAX_VOTERS = 64;

// Paths to circuit artifacts (relative to project root)
const CIRCUITS_DIR = path.join(process.cwd(), 'circuits');

export const CIRCUIT_PATHS = {
  wasm: path.join(CIRCUITS_DIR, 'vote_verifier_js', 'vote_verifier.wasm'),
  zkey: path.join(CIRCUITS_DIR, 'vote_verifier_final.zkey'),
  verificationKey: path.join(CIRCUITS_DIR, 'verification_key.json'),
} as const;
